name: LobbyPlugin
main: es.networkersmc.lobby.LobbyPlugin
version: ${project.version}
load: POSTWORLD
depend: [DenderaBukkit]

author: Alberto Mimbrero
description: Lobby service for the Networkers Minecraft network.
website: https://github.com/NetworkersES/lobby

commands: {}
